### ISSUE TITLE
ValueError: image has wrong mode

### ISSUE THREAD

**Issue by joelostblom** [trevorcampbell/website_diff#22]
[Workflow link](https://github.com/joelostblom/viz-oer/actions/runs/10780451302/job/29896240072?pr=28)

```sh
2024-09-09 20:08:27.408 | INFO     | website_diff.cli:main:81 - Highlighting new images
2024-09-09 20:08:27.408 | INFO     | website_diff.cli:main:83 - Highlighting new image chapter_1_files/figure-html/unnamed-chunk-15-1.png
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/website_diff/cli.py", line 84, in main
    wd.target.image.highlight_add(os.path.join(new, img), os.path.join(diff, img))
  File "/home/runner/.local/lib/python3.10/site-packages/website_diff/target/image.py", line 39, in highlight_add
    _highlight_image(filepath, filepath_out, "limegreen", 0.5)
  File "/home/runner/.local/lib/python3.10/site-packages/website_diff/target/image.py", line 46, in _highlight_image
    bw = ImageEnhance.Color(img).enhance(0.0).convert("RGBA")
  File "/home/runner/.local/lib/python3.10/site-packages/PIL/ImageEnhance.py", line 40, in enhance
    return Image.blend(self.degenerate, self.image, factor)
  File "/home/runner/.local/lib/python3.10/site-packages/PIL/Image.py", line 3540, in blend
    return im1._new(core.blend(im1.im, im2.im, alpha))
ValueError: image has wrong mode
```

To reproduce locally, use https://github.com/joelostblom/viz-oer/tree/1a0c1bcd8f34c24f9bc9e5b2b0ffdf0a35ca5876 and run `website_diff --old . --new pull28/textbook/_book --diff diff28`

**Comment by joelostblom** [comment]
If the goal of this line:

```py
bw = ImageEnhance.Color(img).enhance(0.0).convert("RGBA")
```

is only to convert the image to black and white, then maybe something like this can be used instead?

```py
bw = img.convert("LA").convert("RGBA")
```

This works for me locally with the image that caused the error above.

**Comment by briank-git** [comment]
Thanks Joel, I made a PR with the change. Tested working.

**Comment by joelostblom** [comment]
Great! I made the change in a branch as well and it has been working fine for the diffs I have created so far, but I don't have that much experience with pillow so wasn't 100% if there was some corner case behavior that would be different. But from my side, I like the fix
